### ISSUE TITLE
PFUZE100 PMIC on pico-imx6

### ISSUE THREAD

**Issue by geoffrey-vl** [TechNexion/u-boot-tn-imx#3]
I have a custom PCB with pico-imx6q.
My board boots fine, though during u-boot I noticed the message `Can't find PMIC:PFUZE100`.
To my understanding pico-imx6q doesn't come with a PMIC.
Why does `board/technexion/pico-imx6/pico-imx6.c` and `include/configs/pico-imx6.h` contain configuration for PFUZE100 when there actually isn't one?

**Comment by richard-hu** [comment]
@geoffrey-vl 

Sorry for the late reply.

It recalls what i has done many years ago. 
In PICO-IMX6 family, there is a member called "PICO-IMX6POP-SD".
"PICO-IMX6POP-SD" is with PMIC. 
[picoimx6popsd.pdf](https://ftp.technexion.com/product_datasheets/picoimx6popsd.pdf)

In order to let u-boot compatible with this SOM, We enable PMIC support for it six years ago.
https://github.com/TechNexion/u-boot-edm/commit/7b3e4722c4f5b622ce474e2ee54e5e3ba9194eb8

Duo to some considerations, we stop to support this sku recently.
So, in latest u-boot - `tn-imx_v2020.04_5.4.70_2.3.0-next`, we take out PMIC initialization in pico-imx6.c. 

BR,

Richard

**Comment by geoffrey-vl** [comment]
@richard-hu , that clarifies that part of the code which I've now removed too, thanks for the feedback!
